// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seatrac_driver.proto

#ifndef PROTOBUF_INCLUDED_seatrac_5fdriver_2eproto
#define PROTOBUF_INCLUDED_seatrac_5fdriver_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "goby/acomms/protobuf/modem_message.pb.h"
#include "goby/protobuf/option_extensions.pb.h"
#include "dccl/option_extensions.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_seatrac_5fdriver_2eproto 

namespace protobuf_seatrac_5fdriver_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_seatrac_5fdriver_2eproto
namespace goby {
namespace acomms {
namespace seatrac {
namespace protobuf {
class Transmission;
class TransmissionDefaultTypeInternal;
extern TransmissionDefaultTypeInternal _Transmission_default_instance_;
}  // namespace protobuf
}  // namespace seatrac
}  // namespace acomms
}  // namespace goby
namespace google {
namespace protobuf {
template<> ::goby::acomms::seatrac::protobuf::Transmission* Arena::CreateMaybeMessage<::goby::acomms::seatrac::protobuf::Transmission>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace goby {
namespace acomms {
namespace seatrac {
namespace protobuf {

enum TransmissionType {
  BASE_TYPE = 0,
  SEATRAC_TWO_WAY_PING = 1,
  SEATRAC_NAVIGATION = 2,
  SEATRAC_ECHO = 3
};
bool TransmissionType_IsValid(int value);
const TransmissionType TransmissionType_MIN = BASE_TYPE;
const TransmissionType TransmissionType_MAX = SEATRAC_ECHO;
const int TransmissionType_ARRAYSIZE = TransmissionType_MAX + 1;

const ::google::protobuf::EnumDescriptor* TransmissionType_descriptor();
inline const ::std::string& TransmissionType_Name(TransmissionType value) {
  return ::google::protobuf::internal::NameOfEnum(
    TransmissionType_descriptor(), value);
}
inline bool TransmissionType_Parse(
    const ::std::string& name, TransmissionType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TransmissionType>(
    TransmissionType_descriptor(), name, value);
}
// ===================================================================

class Transmission : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:goby.acomms.seatrac.protobuf.Transmission) */ {
 public:
  Transmission();
  virtual ~Transmission();

  Transmission(const Transmission& from);

  inline Transmission& operator=(const Transmission& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Transmission(Transmission&& from) noexcept
    : Transmission() {
    *this = ::std::move(from);
  }

  inline Transmission& operator=(Transmission&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Transmission& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Transmission* internal_default_instance() {
    return reinterpret_cast<const Transmission*>(
               &_Transmission_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Transmission* other);
  friend void swap(Transmission& a, Transmission& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Transmission* New() const final {
    return CreateMaybeMessage<Transmission>(NULL);
  }

  Transmission* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Transmission>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Transmission& from);
  void MergeFrom(const Transmission& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Transmission* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .goby.acomms.seatrac.protobuf.TransmissionType type = 1 [default = BASE_TYPE, (.goby.field) = {
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::goby::acomms::seatrac::protobuf::TransmissionType type() const;
  void set_type(::goby::acomms::seatrac::protobuf::TransmissionType value);

  // @@protoc_insertion_point(class_scope:goby.acomms.seatrac.protobuf.Transmission)
 private:
  void set_has_type();
  void clear_has_type();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  int type_;
  friend struct ::protobuf_seatrac_5fdriver_2eproto::TableStruct;
};
// ===================================================================

static const int kTransmissionFieldNumber = 1520;
extern ::google::protobuf::internal::ExtensionIdentifier< ::goby::acomms::protobuf::ModemTransmission,
    ::google::protobuf::internal::MessageTypeTraits< ::goby::acomms::seatrac::protobuf::Transmission >, 11, false >
  transmission;

// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Transmission

// optional .goby.acomms.seatrac.protobuf.TransmissionType type = 1 [default = BASE_TYPE, (.goby.field) = {
inline bool Transmission::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Transmission::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Transmission::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Transmission::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::goby::acomms::seatrac::protobuf::TransmissionType Transmission::type() const {
  // @@protoc_insertion_point(field_get:goby.acomms.seatrac.protobuf.Transmission.type)
  return static_cast< ::goby::acomms::seatrac::protobuf::TransmissionType >(type_);
}
inline void Transmission::set_type(::goby::acomms::seatrac::protobuf::TransmissionType value) {
  assert(::goby::acomms::seatrac::protobuf::TransmissionType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:goby.acomms.seatrac.protobuf.Transmission.type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace seatrac
}  // namespace acomms
}  // namespace goby

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::goby::acomms::seatrac::protobuf::TransmissionType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::goby::acomms::seatrac::protobuf::TransmissionType>() {
  return ::goby::acomms::seatrac::protobuf::TransmissionType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_seatrac_5fdriver_2eproto
