
goby:
  driver: "evologics"
  max_frame_bytes: 500
  mac_slot_time: 5

  
  dynamic_buffer:
    #select the messages to load to the dynamic buffer
    messages: ["example", "pose_command", "power_command"]

    #buffer configuration (https://goby.software/3.0/md_doc101_acomms-queue.html)
    example:
      ack: false
      blackout_time: 0
      max_queue: 1
      newest_first: true 
      ttl: 1800
      value_base: 1

    pose_command:
      ack: false
      blackout_time: 0
      max_queue: 1
      newest_first: true 
      ttl: 1800
      value_base: 1

    power_command:
      ack: false
      blackout_time: 0
      max_queue: 1
      newest_first: true 
      ttl: 1800
      value_base: 1


