
###################################################################
###################### Configuration ##############################
###################################################################


type: "modem"

usbl_configuration:

  interface:

    device: /dev/ttyUSB0
    baudrate: 115200

  device_id: 15

  auto_sound_speed: false
  sound_speed: 1500


modem_configuration:

  interface:

    device: /dev/ttyUSB0
    baudrate: 115200

  device_id: 1





  