#ifndef ALPHA_ACOMMS_COMMON
#define ALPHA_ACOMMS_COMMON


enum DcclIdMap
{
    POSE_COMMAND_ID             = 1,
    POSE_RESPONSE_ID            = 101,
    POWER_COMMAND_ID            = 2,
    POWER_RESPONSE_ID           = 102,
    RELATIVE_POSE_COMMAND_ID    = 3,
    RELATIVE_POSE_RESPONSE_ID   = 103,
    CONTROLLER_STATE_COMMAND_ID = 4,
    CONTROLLER_STATE_RESPONSE_ID = 104,
    DIRECT_CONTROL_COMMAND_ID   = 5,
    HELM_STATE_COMMAND_ID       = 6,
    HELM_STATE_RESPONSE_ID      = 106,
    WAYPOINT_COMMAND_ID         = 7,
    WAYPOINT_RESPONSE_ID        = 107,
    EXECUTE_WAYPOINTS_ID        = 8
};

#endif
